import { Product } from '@/types/product-type';
import { CategoryType, SellerProductListType } from '@/types/types';

export const dummyOrders = [
  {
    id: 1,
    name: 'Order 1',
    status: 'new',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jne',
    createdAt: '2024-12-02T02:05:07.303Z',
    updatedAt: '2024-12-02T02:05:07.303Z',
  },
  {
    id: 2,
    name: 'Order 2',
    status: 'unpaid',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'anteraja',
    createdAt: '2024-12-02T02:05:07.303Z',
    updatedAt: '2024-12-02T02:05:07.303Z',
  },
  {
    id: 3,
    name: 'Order 3',
    status: 'unpaid',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jne',
    createdAt: '2024-11-02T02:05:07.303Z',
    updatedAt: '2024-11-02T02:05:07.303Z',
  },
  {
    id: 4,
    name: 'Order 4',
    status: 'new',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jnt',
    createdAt: '2024-11-02T02:05:07.303Z',
    updatedAt: '2024-11-02T02:05:07.303Z',
  },
  {
    id: 5,
    name: 'Order 5',
    status: 'ready',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jnt',
    createdAt: '2024-10-02T02:05:07.303Z',
    updatedAt: '2024-10-02T02:05:07.303Z',
  },
  {
    id: 6,
    name: 'Order 6',
    status: 'ready',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jne',
    createdAt: '2024-10-02T02:05:07.303Z',
    updatedAt: '2024-10-02T02:05:07.303Z',
  },
  {
    id: 7,
    name: 'Order 7',
    status: 'delivery',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'anteraja',
    createdAt: '2024-09-02T02:05:07.303Z',
    updatedAt: '2024-09-02T02:05:07.303Z',
  },
  {
    id: 8,
    name: 'Order 8',
    status: 'delivery',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'anteraja',
    createdAt: '2024-09-02T02:05:07.303Z',
    updatedAt: '2024-09-02T02:05:07.303Z',
  },
  {
    id: 10,
    name: 'Order 10',
    status: 'canceled',
    invoice: 'INV/20230809/MPL/00000239',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
    courier: 'jnt',
    createdAt: '2024-08-02T02:05:07.303Z',
    updatedAt: '2024-08-02T02:05:07.303Z',
  },
];

export const dummyOrderDetail = [
  {
    id: 1,
    name: 'Order 1',
    status: 'new',
    invoice: 'INV/20241201/MPL/000001',
    customer: 'John Doe',
    createdAt: '2024-12-01',
    address: '123 Main St, Metropolis',
    courier: 'jne',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 2,
    name: 'Order 2',
    status: 'unpaid',
    invoice: 'INV/20241203/MPL/000002',
    customer: 'Jane Smith',
    createdAt: '2024-12-03',
    address: '456 Elm St, Gotham',
    courier: 'anteraja',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 3,
    name: 'Order 3',
    status: 'unpaid',
    invoice: 'INV/20241205/MPL/000003',
    customer: 'Alice Johnson',
    createdAt: '2024-12-05',
    address: '789 Oak St, Star City',
    courier: 'jne',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 4,
    name: 'Order 4',
    status: 'new',
    invoice: 'INV/20241207/MPL/000004',
    customer: 'Bob Brown',
    createdAt: '2024-12-07',
    address: '101 Pine St, Central City',
    courier: 'jnt',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 5,
    name: 'Order 5',
    status: 'ready',
    invoice: 'INV/20241208/MPL/000005',
    customer: 'Charlie White',
    createdAt: '2024-12-08',
    address: '202 Maple St, Coast City',
    courier: 'jnt',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 6,
    name: 'Order 6',
    status: 'ready',
    invoice: 'INV/20241209/MPL/000006',
    customer: 'Diana Prince',
    createdAt: '2024-12-09',
    address: '303 Birch St, Keystone City',
    courier: 'jne',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 7,
    name: 'Order 7',
    status: 'delivery',
    invoice: 'INV/20241210/MPL/000007',
    customer: 'Clark Kent',
    createdAt: '2024-12-10',
    address: '404 Cedar St, Smallville',
    courier: 'anteraja',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
  {
    id: 8,
    name: 'Order 8',
    status: 'delivery',
    invoice: 'INV/20241211/MPL/000008',
    customer: 'Bruce Wayne',
    createdAt: '2024-12-11',
    address: '505 Walnut St, Gotham',
    courier: 'anteraja',
    quantity: 4,
    total_price: 2200000,
    image: {
      src: 'https://down-id.img.susercontent.com/file/sg-11134201-22110-xhtlq7aviojvf9',
      alt: 'gambar keren nih',
    },
  },
];

export const dummyProducts: SellerProductListType[] = [
  {
    id: '1',
    name: 'SMARTPHONE PRO MAX',
    is_active: true,
    price: 999.99,
    stock: 15,
    sku: 'SPM-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Smartphone Pro Max',
      },
    ],
    url_name: '/smartphone-pro-max',
    Category: {
      children: [],
      id: 'cat-2',
      label: 'Smartphones',
      value: 'smartphones',
      parent_id: 'cat-1',
    },
    created_at: '2024-01-01T00:00:00.000Z',
    updated_at: '2024-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    name: 'ULTRABOOK X9',
    is_active: false,
    price: 1299.99,
    stock: 10,
    sku: 'UBX9-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Ultrabook X9',
      },
    ],
    url_name: '/ultrabook-x9',
    Category: {
      children: [],
      id: 'cat-3',
      label: 'Laptops',
      value: 'laptops',
      parent_id: 'cat-1',
    },
    created_at: '2024-01-02T00:00:00.000Z',
    updated_at: '2024-01-02T00:00:00.000Z',
  },
  {
    id: '3',
    name: 'TABLET GEN 3',
    is_active: false,
    price: 499.99,
    stock: 25,
    sku: 'TABGEN3-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Tablet Gen 3',
      },
    ],
    url_name: '/tablet-gen-3',
    Category: {
      children: [],
      id: 'cat-4',
      label: 'Tablets',
      value: 'tablets',
      parent_id: 'cat-1',
    },
    created_at: '2025-01-03T00:00:00.000Z',
    updated_at: '2025-01-03T00:00:00.000Z',
  },
  {
    id: '4',
    name: 'HD CAMERA 4K',
    is_active: false,
    price: 399.99,
    stock: 20,
    sku: 'CAM4K-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'HD Camera 4K',
      },
    ],
    url_name: '/hd-camera-4k',
    Category: {
      children: [],
      id: 'cat-5',
      label: 'Cameras',
      value: 'cameras',
      parent_id: 'cat-1',
    },
    created_at: '2024-01-04T00:00:00.000Z',
    updated_at: '2024-01-04T00:00:00.000Z',
  },
  {
    id: '5',
    name: 'WIRELESS HEADPHONES X',
    is_active: false,
    price: 199.99,
    stock: 50,
    sku: 'WHX-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Wireless Headphones X',
      },
    ],
    url_name: '/wireless-headphones-x',
    Category: {
      children: [],
      id: 'cat-6',
      label: 'Headphones',
      value: 'headphones',
      parent_id: 'cat-1',
    },
    created_at: '2024-01-05T00:00:00.000Z',
    updated_at: '2024-01-05T00:00:00.000Z',
  },
  {
    id: '6',
    name: 'DOUBLE DOOR REFRIGERATOR',
    is_active: false,
    price: 899.99,
    stock: 8,
    sku: 'DDR-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Double Door Refrigerator',
      },
    ],
    url_name: '/double-door-refrigerator',
    Category: {
      children: [],
      id: 'cat-8',
      label: 'Refrigerators',
      value: 'refrigerators',
      parent_id: 'cat-7',
    },
    created_at: '2024-01-06T00:00:00.000Z',
    updated_at: '2024-01-06T00:00:00.000Z',
  },
  {
    id: '7',
    name: 'WASHING MACHINE PLUS',
    is_active: false,
    price: 499.99,
    stock: 12,
    sku: 'WMPLUS-2024',
    Images: [
      {
        src: 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/01/03/904180906.jpg',
        alt: 'Washing Machine Plus',
      },
    ],
    url_name: '/washing-machine-plus',
    Category: {
      children: [],
      id: 'cat-10',
      label: 'Washing Machines',
      value: 'washing-machines',
      parent_id: 'cat-7',
    },
    created_at: '2024-01-07T00:00:00.000Z',
    updated_at: '2024-01-07T00:00:00.000Z',
  },
];
export const dummyCategories: CategoryType[] = [
  {
    id: 'cat-1',
    label: 'Electronic',
    value: 'electronic',
    parent_id: null,
    children: [
      {
        id: 'cat-2',
        parent_id: 'cat-1',
        label: 'Mobile',
        value: 'mobile',
      },
      {
        id: 'cat-5',
        parent_id: 'cat-1',
        label: 'Laptops',
        value: 'laptops',
      },
      {
        id: 'cat-8',
        parent_id: 'cat-1',
        label: 'Accessories',
        value: 'accessories',
      },
    ],
  },
  {
    id: 'cat-2',
    label: 'Mobile',
    value: 'mobile',
    parent_id: null,
    children: [
      {
        id: 'cat-3',
        parent_id: 'cat-2',
        label: 'Smartphones',
        value: 'smartphones',
      },
      {
        id: 'cat-4',
        parent_id: 'cat-2',
        label: 'Feature Phones',
        value: 'feature-phones',
      },
    ],
  },
  {
    id: 'cat-3',
    label: 'Smartphones',
    value: 'smartphones',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-4',
    label: 'Feature Phones',
    value: 'feature-phones',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-5',
    label: 'Laptops',
    value: 'laptops',
    parent_id: null,
    children: [
      {
        id: 'cat-6',
        parent_id: 'cat-5',
        label: 'Gaming Laptops',
        value: 'gaming-laptops',
      },
      {
        id: 'cat-7',
        parent_id: 'cat-5',
        label: 'Ultrabooks',
        value: 'ultrabooks',
      },
    ],
  },
  {
    id: 'cat-6',
    label: 'Gaming Laptops',
    value: 'gaming-laptops',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-7',
    label: 'Ultrabooks',
    value: 'ultrabooks',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-8',
    label: 'Accessories',
    value: 'accessories',
    parent_id: null,
    children: [
      {
        id: 'cat-9',
        parent_id: 'cat-8',
        label: 'Chargers',
        value: 'chargers',
      },
      {
        id: 'cat-10',
        parent_id: 'cat-8',
        label: 'Cables',
        value: 'cables',
      },
    ],
  },
  {
    id: 'cat-9',
    label: 'Chargers',
    value: 'chargers',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-10',
    label: 'Cables',
    value: 'cables',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-11',
    label: 'Fashion',
    value: 'fashion',
    parent_id: null,
    children: [
      {
        id: 'cat-12',
        parent_id: 'cat-11',
        label: "Men's Clothing",
        value: 'mens-clothing',
      },
      {
        id: 'cat-15',
        parent_id: 'cat-11',
        label: "Women's Clothing",
        value: 'womens-clothing',
      },
    ],
  },
  {
    id: 'cat-12',
    label: "Men's Clothing",
    value: 'mens-clothing',
    parent_id: null,
    children: [
      {
        id: 'cat-13',
        parent_id: 'cat-12',
        label: 'Shirts',
        value: 'shirts',
      },
      {
        id: 'cat-14',
        parent_id: 'cat-12',
        label: 'Trousers',
        value: 'trousers',
      },
    ],
  },
  {
    id: 'cat-13',
    label: 'Shirts',
    value: 'shirts',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-14',
    label: 'Trousers',
    value: 'trousers',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-15',
    label: "Women's Clothing",
    value: 'womens-clothing',
    parent_id: null,
    children: [
      {
        id: 'cat-16',
        parent_id: 'cat-15',
        label: 'Dresses',
        value: 'dresses',
      },
      {
        id: 'cat-17',
        parent_id: 'cat-15',
        label: 'Skirts',
        value: 'skirts',
      },
    ],
  },
  {
    id: 'cat-16',
    label: 'Dresses',
    value: 'dresses',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-17',
    label: 'Skirts',
    value: 'skirts',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-18',
    label: 'Home Appliances',
    value: 'home-appliances',
    parent_id: null,
    children: [
      {
        id: 'cat-19',
        parent_id: 'cat-18',
        label: 'Kitchen Appliances',
        value: 'kitchen-appliances',
      },
      {
        id: 'cat-20',
        parent_id: 'cat-18',
        label: 'Vacuum Cleaners',
        value: 'vacuum-cleaners',
      },
      {
        id: 'cat-23',
        parent_id: 'cat-18',
        label: 'Laundry',
        value: 'laundry',
      },
    ],
  },
  {
    id: 'cat-19',
    label: 'Kitchen Appliances',
    value: 'kitchen-appliances',
    parent_id: null,
    children: [
      {
        id: 'cat-21',
        parent_id: 'cat-19',
        label: 'Microwaves',
        value: 'microwaves',
      },
      {
        id: 'cat-22',
        parent_id: 'cat-19',
        label: 'Blenders',
        value: 'blenders',
      },
    ],
  },
  {
    id: 'cat-20',
    label: 'Vacuum Cleaners',
    value: 'vacuum-cleaners',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-21',
    label: 'Microwaves',
    value: 'microwaves',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-22',
    label: 'Blenders',
    value: 'blenders',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-23',
    label: 'Laundry',
    value: 'laundry',
    parent_id: null,
    children: [
      {
        id: 'cat-24',
        parent_id: 'cat-23',
        label: 'Washing Machines',
        value: 'washing-machines',
      },
      {
        id: 'cat-25',
        parent_id: 'cat-23',
        label: 'Dryers',
        value: 'dryers',
      },
    ],
  },
  {
    id: 'cat-24',
    label: 'Washing Machines',
    value: 'washing-machines',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-25',
    label: 'Dryers',
    value: 'dryers',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-26',
    label: 'Books',
    value: 'books',
    parent_id: null,
    children: [
      {
        id: 'cat-27',
        parent_id: 'cat-26',
        label: 'Fiction',
        value: 'fiction',
      },
      {
        id: 'cat-28',
        parent_id: 'cat-26',
        label: 'Non-Fiction',
        value: 'non-fiction',
      },
    ],
  },
  {
    id: 'cat-27',
    label: 'Fiction',
    value: 'fiction',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-28',
    label: 'Non-Fiction',
    value: 'non-fiction',
    parent_id: null,
    children: [
      {
        id: 'cat-29',
        parent_id: 'cat-28',
        label: 'Biographies',
        value: 'biographies',
      },
      {
        id: 'cat-30',
        parent_id: 'cat-28',
        label: 'Self-Help',
        value: 'self-help',
      },
    ],
  },
  {
    id: 'cat-29',
    label: 'Biographies',
    value: 'biographies',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-30',
    label: 'Self-Help',
    value: 'self-help',
    children: [],
    parent_id: null,
  },
  {
    id: 'cat-31',
    label: 'Sports & Outdoors',
    value: 'sports-outdoors',
    parent_id: null,
    children: [
      {
        id: 'cat-32',
        parent_id: 'cat-31',
        label: 'Fitness Equipment',
        value: 'fitness-equipment',
      },
      {
        id: 'cat-33',
        parent_id: 'cat-31',
        label: 'Outdoor Gear',
        value: 'outdoor-gear',
      },
    ],
  },
  {
    id: 'cat-32',
    label: 'Fitness Equipment',
    value: 'fitness-equipment',
    parent_id: null,
    children: [
      {
        id: 'cat-34',
        parent_id: 'cat-32',
        label: 'Treadmills',
        value: 'treadmills',
      },
      {
        id: 'cat-35',
        parent_id: 'cat-32',
        label: 'Dumbbells',
        value: 'dumbbells',
      },
    ],
  },
  {
    id: 'cat-33',
    label: 'Outdoor Gear',
    value: 'outdoor-gear',
    parent_id: null,
    children: [
      {
        id: 'cat-36',
        parent_id: 'cat-33',
        label: 'Camping Tents',
        value: 'camping-tents',
      },
      {
        id: 'cat-37',
        parent_id: 'cat-33',
        label: 'Backpacks',
        value: 'backpacks',
      },
    ],
  },
  {
    id: 'cat-34',
    label: 'Treadmills',
    value: 'treadmills',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-35',
    label: 'Dumbbells',
    value: 'dumbbells',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-36',
    label: 'Camping Tents',
    value: 'camping-tents',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-37',
    label: 'Backpacks',
    value: 'backpacks',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-38',
    label: 'Toys & Games',
    value: 'toys-games',
    parent_id: null,
    children: [
      {
        id: 'cat-39',
        parent_id: 'cat-38',
        label: 'Action Figures',
        value: 'action-figures',
      },
      {
        id: 'cat-40',
        parent_id: 'cat-38',
        label: 'Board Games',
        value: 'board-games',
      },
    ],
  },
  {
    id: 'cat-39',
    label: 'Action Figures',
    value: 'action-figures',
    parent_id: null,
    children: [
      {
        id: 'cat-41',
        parent_id: 'cat-39',
        label: 'Superheroes',
        value: 'superheroes',
      },
      {
        id: 'cat-42',
        parent_id: 'cat-39',
        label: 'Animals',
        value: 'animals',
      },
    ],
  },
  {
    id: 'cat-40',
    label: 'Board Games',
    value: 'board-games',
    parent_id: null,
    children: [
      {
        id: 'cat-43',
        parent_id: 'cat-40',
        label: 'Strategy Games',
        value: 'strategy-games',
      },
      {
        id: 'cat-44',
        parent_id: 'cat-40',
        label: 'Party Games',
        value: 'party-games',
      },
    ],
  },
  {
    id: 'cat-41',
    label: 'Superheroes',
    value: 'superheroes',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-42',
    label: 'Animals',
    value: 'animals',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-43',
    label: 'Strategy Games',
    value: 'strategy-games',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-44',
    label: 'Party Games',
    value: 'party-games',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-45',
    label: 'Health & Beauty',
    value: 'health-beauty',
    parent_id: null,
    children: [
      {
        id: 'cat-46',
        parent_id: 'cat-45',
        label: 'Skincare',
        value: 'skincare',
      },
      {
        id: 'cat-47',
        parent_id: 'cat-45',
        label: 'Haircare',
        value: 'haircare',
      },
    ],
  },
  {
    id: 'cat-46',
    label: 'Skincare',
    value: 'skincare',
    parent_id: null,
    children: [
      {
        id: 'cat-48',
        parent_id: 'cat-46',
        label: 'Moisturizers',
        value: 'moisturizers',
      },
      {
        id: 'cat-49',
        parent_id: 'cat-46',
        label: 'Sunscreens',
        value: 'sunscreens',
      },
    ],
  },
  {
    id: 'cat-47',
    label: 'Haircare',
    value: 'haircare',
    parent_id: null,
    children: [
      {
        id: 'cat-50',
        parent_id: 'cat-47',
        label: 'Shampoos',
        value: 'shampoos',
      },
      {
        id: 'cat-51',
        parent_id: 'cat-47',
        label: 'Conditioners',
        value: 'conditioners',
      },
    ],
  },
  {
    id: 'cat-48',
    label: 'Moisturizers',
    value: 'moisturizers',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-49',
    label: 'Sunscreens',
    value: 'sunscreens',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-50',
    label: 'Shampoos',
    value: 'shampoos',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-51',
    label: 'Conditioners',
    value: 'conditioners',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-52',
    label: 'Automotive',
    value: 'automotive',
    parent_id: null,
    children: [
      {
        id: 'cat-53',
        parent_id: 'cat-52',
        label: 'Car Accessories',
        value: 'car-accessories',
      },
      {
        id: 'cat-54',
        parent_id: 'cat-52',
        label: 'Motorcycle Accessories',
        value: 'motorcycle-accessories',
      },
    ],
  },
  {
    id: 'cat-53',
    label: 'Car Accessories',
    value: 'car-accessories',
    parent_id: null,
    children: [
      {
        id: 'cat-55',
        parent_id: 'cat-53',
        label: 'Car Covers',
        value: 'car-covers',
      },
      {
        id: 'cat-56',
        parent_id: 'cat-53',
        label: 'Dashboard Accessories',
        value: 'dashboard-accessories',
      },
    ],
  },
  {
    id: 'cat-54',
    label: 'Motorcycle Accessories',
    value: 'motorcycle-accessories',
    parent_id: null,
    children: [
      {
        id: 'cat-57',
        parent_id: 'cat-54',
        label: 'Helmets',
        value: 'helmets',
      },
      {
        id: 'cat-58',
        parent_id: 'cat-54',
        label: 'Riding Gloves',
        value: 'riding-gloves',
      },
    ],
  },
  {
    id: 'cat-55',
    label: 'Car Covers',
    value: 'car-covers',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-56',
    label: 'Dashboard Accessories',
    value: 'dashboard-accessories',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-57',
    label: 'Helmets',
    value: 'helmets',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-58',
    label: 'Riding Gloves',
    value: 'riding-gloves',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-59',
    label: 'Groceries',
    value: 'groceries',
    parent_id: null,
    children: [
      {
        id: 'cat-60',
        parent_id: 'cat-59',
        label: 'Beverages',
        value: 'beverages',
      },
      {
        id: 'cat-61',
        parent_id: 'cat-59',
        label: 'Snacks',
        value: 'snacks',
      },
    ],
  },
  {
    id: 'cat-60',
    label: 'Beverages',
    value: 'beverages',
    parent_id: null,
    children: [
      {
        id: 'cat-62',
        parent_id: 'cat-60',
        label: 'Tea & Coffee',
        value: 'tea-coffee',
      },
      {
        id: 'cat-63',
        parent_id: 'cat-60',
        label: 'Juices',
        value: 'juices',
      },
    ],
  },
  {
    id: 'cat-61',
    label: 'Snacks',
    value: 'snacks',
    parent_id: null,
    children: [
      {
        id: 'cat-64',
        parent_id: 'cat-61',
        label: 'Chips',
        value: 'chips',
      },
      {
        id: 'cat-65',
        parent_id: 'cat-61',
        label: 'Biscuits',
        value: 'biscuits',
      },
    ],
  },
  {
    id: 'cat-62',
    label: 'Tea & Coffee',
    value: 'tea-coffee',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-63',
    label: 'Juices',
    value: 'juices',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-64',
    label: 'Chips',
    value: 'chips',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-65',
    label: 'Biscuits',
    value: 'biscuits',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-66',
    label: 'Pets',
    value: 'pets',
    parent_id: null,
    children: [
      {
        id: 'cat-67',
        parent_id: 'cat-66',
        label: 'Pet Food',
        value: 'pet-food',
      },
      {
        id: 'cat-68',
        parent_id: 'cat-66',
        label: 'Pet Toys',
        value: 'pet-toys',
      },
    ],
  },
  {
    id: 'cat-67',
    label: 'Pet Food',
    value: 'pet-food',
    parent_id: null,
    children: [
      {
        id: 'cat-69',
        parent_id: 'cat-67',
        label: 'Dog Food',
        value: 'dog-food',
      },
      {
        id: 'cat-70',
        parent_id: 'cat-67',
        label: 'Cat Food',
        value: 'cat-food',
      },
    ],
  },
  {
    id: 'cat-68',
    label: 'Pet Toys',
    value: 'pet-toys',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-69',
    label: 'Dog Food',
    value: 'dog-food',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-70',
    label: 'Cat Food',
    value: 'cat-food',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-71',
    label: 'Office Supplies',
    value: 'office-supplies',
    parent_id: null,
    children: [
      {
        id: 'cat-72',
        parent_id: 'cat-71',
        label: 'Stationery',
        value: 'stationery',
      },
      {
        id: 'cat-73',
        parent_id: 'cat-71',
        label: 'Desk Organizers',
        value: 'desk-organizers',
      },
    ],
  },
  {
    id: 'cat-72',
    label: 'Stationery',
    value: 'stationery',
    parent_id: null,
    children: [
      {
        id: 'cat-74',
        parent_id: 'cat-72',
        label: 'Pens & Pencils',
        value: 'pens-pencils',
      },
      {
        id: 'cat-75',
        parent_id: 'cat-72',
        label: 'Notebooks',
        value: 'notebooks',
      },
    ],
  },
  {
    id: 'cat-73',
    label: 'Desk Organizers',
    value: 'desk-organizers',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-74',
    label: 'Pens & Pencils',
    value: 'pens-pencils',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-75',
    label: 'Notebooks',
    value: 'notebooks',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-76',
    label: 'Travel',
    value: 'travel',
    parent_id: null,
    children: [
      {
        id: 'cat-77',
        parent_id: 'cat-76',
        label: 'Luggage',
        value: 'luggage',
      },
      {
        id: 'cat-78',
        parent_id: 'cat-76',
        label: 'Travel Accessories',
        value: 'travel-accessories',
      },
    ],
  },
  {
    id: 'cat-77',
    label: 'Luggage',
    value: 'luggage',
    parent_id: null,
    children: [
      {
        id: 'cat-79',
        parent_id: 'cat-77',
        label: 'Suitcases',
        value: 'suitcases',
      },
      {
        id: 'cat-80',
        parent_id: 'cat-77',
        label: 'Travel Backpacks',
        value: 'travel-backpacks',
      },
    ],
  },
  {
    id: 'cat-78',
    label: 'Travel Accessories',
    value: 'travel-accessories',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-79',
    label: 'Suitcases',
    value: 'suitcases',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-80',
    label: 'Travel Backpacks',
    value: 'travel-backpacks',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-81',
    label: 'Music',
    value: 'music',
    parent_id: null,
    children: [
      {
        id: 'cat-82',
        parent_id: 'cat-81',
        label: 'Instruments',
        value: 'instruments',
      },
      {
        id: 'cat-83',
        parent_id: 'cat-81',
        label: 'Accessories',
        value: 'music-accessories',
      },
    ],
  },
  {
    id: 'cat-82',
    label: 'Instruments',
    value: 'instruments',
    parent_id: null,
    children: [
      {
        id: 'cat-84',
        parent_id: 'cat-82',
        label: 'Guitars',
        value: 'guitars',
      },
      {
        id: 'cat-85',
        parent_id: 'cat-82',
        label: 'Pianos',
        value: 'pianos',
      },
    ],
  },
  {
    id: 'cat-83',
    label: 'Accessories',
    value: 'music-accessories',
    parent_id: null,
    children: [
      {
        id: 'cat-86',
        parent_id: 'cat-83',
        label: 'Stands',
        value: 'stands',
      },
      {
        id: 'cat-87',
        parent_id: 'cat-83',
        label: 'Cables',
        value: 'music-cables',
      },
    ],
  },
  {
    id: 'cat-84',
    label: 'Guitars',
    value: 'guitars',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-85',
    label: 'Pianos',
    value: 'pianos',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-86',
    label: 'Stands',
    value: 'stands',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-87',
    label: 'Cables',
    value: 'music-cables',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-88',
    label: 'Art',
    value: 'art',
    parent_id: null,
    children: [
      {
        id: 'cat-89',
        parent_id: 'cat-88',
        label: 'Paints',
        value: 'paints',
      },
      {
        id: 'cat-90',
        parent_id: 'cat-88',
        label: 'Brushes',
        value: 'brushes',
      },
    ],
  },
  {
    id: 'cat-89',
    label: 'Paints',
    value: 'paints',
    parent_id: null,
    children: [
      {
        id: 'cat-91',
        parent_id: 'cat-89',
        label: 'Acrylic',
        value: 'acrylic-paints',
      },
      {
        id: 'cat-92',
        parent_id: 'cat-89',
        label: 'Watercolor',
        value: 'watercolor-paints',
      },
    ],
  },
  {
    id: 'cat-90',
    label: 'Brushes',
    value: 'brushes',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-91',
    label: 'Acrylic',
    value: 'acrylic-paints',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-92',
    label: 'Watercolor',
    value: 'watercolor-paints',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-93',
    label: 'Baby Products',
    value: 'baby-products',
    parent_id: null,
    children: [
      {
        id: 'cat-94',
        parent_id: 'cat-93',
        label: 'Diapers',
        value: 'diapers',
      },
      {
        id: 'cat-95',
        parent_id: 'cat-93',
        label: 'Toys',
        value: 'baby-toys',
      },
    ],
  },
  {
    id: 'cat-94',
    label: 'Diapers',
    value: 'diapers',
    parent_id: null,
    children: [
      {
        id: 'cat-96',
        parent_id: 'cat-94',
        label: 'Newborn Diapers',
        value: 'newborn-diapers',
      },
      {
        id: 'cat-97',
        parent_id: 'cat-94',
        label: 'Reusable Diapers',
        value: 'reusable-diapers',
      },
    ],
  },
  {
    id: 'cat-95',
    label: 'Toys',
    value: 'baby-toys',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-96',
    label: 'Newborn Diapers',
    value: 'newborn-diapers',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-97',
    label: 'Reusable Diapers',
    value: 'reusable-diapers',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-98',
    label: 'Furniture',
    value: 'furniture',
    parent_id: null,
    children: [
      {
        id: 'cat-99',
        parent_id: 'cat-98',
        label: 'Living Room',
        value: 'living-room',
      },
      {
        id: 'cat-100',
        parent_id: 'cat-98',
        label: 'Bedroom',
        value: 'bedroom',
      },
    ],
  },
  {
    id: 'cat-99',
    label: 'Living Room',
    value: 'living-room',
    parent_id: null,
    children: [],
  },
  {
    id: 'cat-100',
    label: 'Bedroom',
    value: 'bedroom',
    parent_id: null,
    children: [],
  },
];

export const dummyCouriers = [
  { id: 'courier-1', label: 'Jne', value: 'jne' },
  { id: 'courier-2', label: 'Anter aja', value: 'anteraja' },
  { id: 'courier-3', label: 'Jnt', value: 'jnt' },
];

export const dummySorts = [
  { label: 'Newest', value: 'new' },
  { label: 'Oldest', value: 'old' },
];

export const dummyVariants = [
  {
    id: 'variant-1',
    name: 'color',
    variantOption: [
      {
        id: 'variant-1-1',
        image: { src: 'https://example.com/images/white.jpg', alt: 'White' },
        variantOptionValue: [
          {
            name: 'White',
            sku: 'SKU123123',
            weight: 2,
            stock: 10,
            price: 100000,
            is_active: true,
          },
        ],
      },
      {
        id: 'name',
        image: { src: 'https://example.com/images/white.jpg', alt: 'Blacl' },
        variantOptionValue: [
          {
            name: 'White',
            sku: 'SKU123123',
            weight: 2,
            stock: 10,
            price: 100000,
            is_active: true,
          },
        ],
      },
      {
        id: 'name',
        image: { src: 'https://example.com/images/white.jpg', alt: 'White' },
        variantOptionValue: [
          {
            name: 'White',
            sku: 'SKU123123',
            weight: 2,
            stock: 10,
            price: 100000,
            is_active: true,
          },
        ],
      },
    ],
  },
  {
    id: 'variant-2',
    name: 'size',
    variantOption: [
      {
        id: 'name',
        image: { src: 'https://example.com/images/white.jpg', alt: 'White' },
        variantOptionValue: [
          {
            name: 'White',
            sku: 'SKU123123',
            weight: 2,
            stock: 10,
            price: 100000,
            is_active: true,
          },
        ],
      },
    ],
  },
  {
    id: 'variant-3',
    name: 'package size',
    variantOption: [
      {
        id: 'name',
        image: { src: 'https://example.com/images/white.jpg', alt: 'White' },
        variantOptionValue: [
          {
            name: 'White',
            sku: 'SKU123123',
            weight: 2,
            stock: 10,
            price: 100000,
            is_active: true,
          },
        ],
      },
    ],
  },
];

export const newDummyProductDetail: Product = {
  id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
  category_id: 'cat-2',
  name: 'coba bro',
  sku: '123',
  price: 123,
  url_name: 'coba-bro',
  description: 'wdawdawdawdawdawd',
  stock: 1,
  weight: 123,
  minimum_order: 1,
  is_active: true,
  length: 123,
  width: 123,
  height: 123,
  created_at: '2024-12-18T19:54:51.716Z',
  updated_at: '2024-12-18T19:54:51.716Z',
  Images: [
    {
      id: 'a95ac2f2-be51-4f4f-af2e-2fd977d16242',
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
      src: 'https://res.cloudinary.com/dxkoqosa0/image/upload/v1734551691/mpqdwypz3v8zu7uvgsoh.jpg',
      alt: 'coba bro - 1',
    },
  ],
  Variant: [
    {
      is_active: true,
      product_id: '1',
      id: '0.018197141056536914',
      name: 'Color',
      VariantOption: [
        { id: '1', name: 'red', alt: 'red', src: '' },
        { id: '2', name: 'green', alt: 'green', src: '' },
        { id: '3', name: 'blue', alt: 'blue', src: '' },
      ],
    },
    {
      is_active: true,
      product_id: '1',
      id: '0.879789155458568',
      name: 'Size',
      VariantOption: [
        { id: '1', name: 's', alt: 's', src: '' },
        { id: '2', name: 'm', alt: 'm', src: '' },
        { id: '3', name: 'l', alt: 'l', src: '' },
      ],
    },
  ],
  VariantOptionCombinations: [
    {
      id: '7cff55e7-5f58-4c31-a45e-504befa2f2ae',
      name: 'red - s',
      is_active: true,
      price: 10000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: 'd22c9ef6-8238-4453-9f4a-9919fd04c370',
      name: 'red - m',
      is_active: true,
      price: 10000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: '88c2ee54-e281-4661-aa4e-8f43bc67193f',
      name: 'red - k',
      is_active: true,
      price: 10000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: 'de7e1809-66cd-4b92-ac0a-1121fdd1d6d2',
      name: 'green - s',
      is_active: true,
      price: 200000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: '91936037-b3e3-414a-8726-32c3cdeca5ec',
      name: 'green - m',
      is_active: true,
      price: 200000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: 'c51e31a1-2b54-4274-a3cb-31b7da987a34',
      name: 'green - k',
      is_active: true,
      price: 200000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: '619f7c22-4497-4ac8-8e57-76314be1eeb4',
      name: 'blue - s',
      is_active: true,
      price: 30000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: '2db3162f-1617-4a2e-9976-1e81a5fa37a9',
      name: 'blue - m',
      is_active: true,
      price: 30000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
    {
      id: '9b049667-d2a0-4ed3-8145-06e1182bfec9',
      name: 'blue - k',
      is_active: true,
      price: 30000,
      weight: 123,
      sku: '123',
      stock: 123,
      product_id: 'b9dfd786-dbd4-426a-8043-3a7ff866c0ac',
    },
  ],
  Category: {
    children: [],
    id: 'cat-2',
    label: 'Mobile',
    value: 'mobile',
    parent_id: 'cat-1',
  },
};

export const dummyLoggedUser = {
  id: '2',
  shop_id: '3',
  name: 'Miguel',
  email: 'bCfDy@example.com',
  role: 'SELLER',
};

export const tableData = [
  {
    id: 1,
    name: 'Order 1',
    category: 'Electronics',
    quantity: 4,
    price: 2200000,
    date: '2024-12-01',
    customer: 'John Doe',
    status: 'new',
  },
  {
    id: 2,
    name: 'Order 2',
    category: 'Home Appliances',
    quantity: 4,
    price: 2200000,
    date: '2024-12-03',
    customer: 'Jane Smith',
    status: 'unpaid',
  },
  {
    id: 3,
    name: 'Order 3',
    category: 'Furniture',
    quantity: 4,
    price: 2200000,
    date: '2024-12-05',
    customer: 'Alice Johnson',
    status: 'unpaid',
  },
  {
    id: 4,
    name: 'Order 4',
    category: 'Electronics',
    quantity: 4,
    price: 2200000,
    date: '2024-12-07',
    customer: 'Bob Brown',
    status: 'new',
  },
  {
    id: 5,
    name: 'Order 5',
    category: 'Accessories',
    quantity: 4,
    price: 2200000,
    date: '2024-12-08',
    customer: 'Charlie White',
    status: 'ready',
  },
  {
    id: 6,
    name: 'Order 6',
    category: 'Electronics',
    quantity: 4,
    price: 2200000,
    date: '2024-12-09',
    customer: 'Diana Prince',
    status: 'ready',
  },
  {
    id: 7,
    name: 'Order 7',
    category: 'Kitchen Appliances',
    quantity: 4,
    price: 2200000,
    date: '2024-12-10',
    customer: 'Clark Kent',
    status: 'delivery',
  },
  {
    id: 8,
    name: 'Order 8',
    category: 'Electronics',
    quantity: 4,
    price: 2200000,
    date: '2024-12-11',
    customer: 'Bruce Wayne',
    status: 'delivery',
  },
];

export const showedCategories = [
  {
    id: '1',
    label: 'Electronics',
    image:
      'https://down-id.img.susercontent.com/file/dcd61dcb7c1448a132f49f938b0cb553@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '2',
    label: 'Computer & Accesories',
    image:
      'https://down-id.img.susercontent.com/file/id-50009109-0bd6a9ebd0f2ae9b7e8b9ce7d89897d6@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '3',
    label: 'Handphone & Accesories',
    image:
      'https://down-id.img.susercontent.com/file/5230277eefafad8611aaf703d3e99568@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '4',
    label: 'Man Clothes',
    image:
      'https://down-id.img.susercontent.com/file/04dba508f1ad19629518defb94999ef9@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '5',
    label: 'Man Shoes',
    image:
      'https://down-id.img.susercontent.com/file/3c8ff51aab1692a80c5883972a679168@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '6',
    label: 'Man Bags',
    image:
      'https://down-id.img.susercontent.com/file/47ed832eed0feb62fd28f08c9229440e@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '7',
    label: 'Fashion Accesories',
    image:
      'https://down-id.img.susercontent.com/file/1f18bdfe73df39c66e7326b0a3e08e87@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '8',
    label: 'Watches',
    image:
      'https://down-id.img.susercontent.com/file/2bdf8cf99543342d4ebd8e1bdb576f80@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '9',
    label: 'Health & Medicine',
    image:
      'https://down-id.img.susercontent.com/file/eb7d583e4b72085e71cd21a70ce47d7a@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '10',
    label: 'Hoby & Collections',
    image:
      'https://down-id.img.susercontent.com/file/42394b78fac1169d67c6291973a3b132@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '11',
    label: 'Foods & Drinks',
    image:
      'https://down-id.img.susercontent.com/file/7873b8c3824367239efb02d18eeab4f5@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '12',
    label: 'Care & Beauty',
    image:
      'https://down-id.img.susercontent.com/file/2715b985ae706a4c39a486f83da93c4b@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '13',
    label: 'Home Utensils',
    image:
      'https://down-id.img.susercontent.com/file/c1494110e0383780cdea73ed890e0299@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '14',
    label: 'Woman Clothes',
    image:
      'https://down-id.img.susercontent.com/file/6d63cca7351ba54a2e21c6be1721fa3a@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '15',
    label: 'Muslim Fashions',
    image:
      'https://down-id.img.susercontent.com/file/b98756cdb31eabe3d7664599e24ccc29@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '16',
    label: 'Child & Baby Fashion',
    image:
      'https://down-id.img.susercontent.com/file/9251edd6d6dd98855ff5a99497835d9c@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
  {
    id: '17',
    label: 'Automotive',
    image:
      'https://down-id.img.susercontent.com/file/27838b968afb76ca59dd8e8f57ece91f@resize_w320_nl.webp',
    value: 'awdawd',
    parent_id: 'awdwa',
  },
];
